/**
 * Preview component library.
 *
 * Mirrors the PHP template parts so the static preview stays faithful
 * to what the theme actually renders. WordPress remains the source of
 * truth; this exists so the design can be reviewed without PHP.
 *
 * Each function here corresponds 1:1 to a file in template-parts/.
 */

const A = '../wp-content/themes/rian-cullet/assets';
// Mirrors the constants in functions.php.
const FACTS = { founded: 1996, combined: 65, companies: 35, states: 22 };

const NAV = [
  ['About', 'about.html'],
  ['Cullet', 'glass-cullet.html'],
  ['Process', 'process.html'],
  ['Sustainability', 'sustainability.html'],
  ['Contact', 'contact.html'],
];

/* --- primitives ---------------------------------------------------------- */

function figure({ name, alt, ratio = '', cls = '', w, h, tag = 'figure', eager = false }) {
  const load = eager
    ? 'loading="eager" fetchpriority="high" decoding="async"'
    : 'loading="lazy" decoding="async"';
  const classes = ['rc-figure', ratio, cls].filter(Boolean).join(' ');
  return `<${tag} class="${classes}"><picture>` +
    `<source srcset="${A}/img/${name}.avif" type="image/avif">` +
    `<source srcset="${A}/img/${name}.webp" type="image/webp">` +
    `<img src="${A}/img/${name}.jpg" alt="${alt}" width="${w}" height="${h}" ${load}>` +
    `</picture></${tag}>`;
}

const btn = (label, href, variant = 'primary', arrow = true) =>
  `<a href="${href}" class="rc-btn rc-btn--${variant}">${label}` +
  (arrow ? ' <span class="rc-btn__arrow" aria-hidden="true">&rarr;</span>' : '') + `</a>`;

const link = (label, href) =>
  `<a class="rc-link" href="${href}">${label} <span class="rc-btn__arrow" aria-hidden="true">&rarr;</span></a>`;

const eyebrow = (text, plain = false) =>
  `<p class="rc-eyebrow${plain ? ' rc-eyebrow--plain' : ''}">${text}</p>`;

// Mirrors rc_logo_mark(): the mark beside a live-text wordmark.
const wordmark = (href, lg = false) =>
  `<a class="rc-wordmark${lg ? ' rc-wordmark--lg' : ''}" href="${href}">` +
  `<picture class="rc-wordmark__mark"><source srcset="${A}/img/logo-mark.webp" type="image/webp">` +
  `<img src="${A}/img/logo-mark.png" alt="" width="195" height="192" loading="${lg ? 'lazy' : 'eager'}" decoding="async"></picture>` +
  ` <span class="rc-wordmark__text">Rian Cullet</span></a>`;

/* --- document shell ------------------------------------------------------ */

function head(title, description) {
  return `<!DOCTYPE html>
<html lang="en" class="rc-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<link rel="icon" href="${A}/img/favicon-32.png" sizes="32x32" type="image/png">
<meta name="description" content="${description}">
<!--
  DESIGN PREVIEW. Generated by tools/build-previews.js from the shared
  component library. Do not hand-edit: run the builder instead.
  Fonts and images are the real theme assets; nothing calls a third party.
-->
<link rel="preload" href="${A}/fonts/instrument-serif-400.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="${A}/fonts/instrument-sans-variable.woff2" as="font" type="font/woff2" crossorigin>
${['00-tokens','01-reset','02-typography','03-layout','04-components','05-sections','07-motion']
  .map(f => `<link rel="stylesheet" href="${A}/css/${f}.css">`).join('\n')}
</head>
<body>
<a class="rc-skip-link" href="#rc-main">Skip to content</a>`;
}

function header(current, overHero = false) {
  const items = NAV.map(([label, href]) => {
    const is = href === current;
    return `<li class="rc-nav__item"><a class="rc-nav__link${is ? ' is-current' : ''}" href="${href}"${is ? ' aria-current="page"' : ''}>${label}</a></li>`;
  }).join('\n        ');

  const overlay = NAV.map(([label, href], i) =>
    `<li class="rc-nav-overlay__item" style="--rc-i:${i}"><a class="rc-nav-overlay__link" href="${href}">${label}</a></li>`
  ).join('\n      ');

  return `
<header class="rc-header${overHero ? ' rc-header--over-hero' : ' is-solid'}" data-rc-header>
  <div class="rc-header__inner rc-container rc-container--wide">
    ${wordmark('home.html')}
    <nav class="rc-nav" aria-label="Primary">
      <ul class="rc-nav__list">
        ${items}
      </ul>
    </nav>
    <div class="rc-header__actions">
      <a href="contact.html" class="rc-btn rc-btn--secondary rc-header__cta">Enquire</a>
      <button type="button" class="rc-burger" data-rc-burger aria-expanded="false" aria-controls="rc-nav-overlay">
        <span class="rc-burger__label">Menu</span>
        <span class="rc-burger__bars" aria-hidden="true"><span></span><span></span></span>
      </button>
    </div>
  </div>
</header>

<div class="rc-nav-overlay rc-surface-ink" id="rc-nav-overlay" data-rc-overlay hidden>
  <nav class="rc-nav-overlay__inner rc-container" aria-label="Mobile">
    <ul class="rc-nav-overlay__list">
      ${overlay}
    </ul>
    <div class="rc-nav-overlay__foot">${btn('Send an enquiry', 'contact.html')}</div>
  </nav>
</div>

<main id="rc-main" class="rc-main">`;
}

function footer() {
  const items = NAV.map(([label, href]) => `<li><a href="${href}">${label}</a></li>`).join('\n          ');
  return `
</main>

<footer class="rc-footer rc-surface-ink" data-nav="dark">
  <div class="rc-container rc-container--wide">
    <div class="rc-footer__top">
      <div class="rc-footer__brand">
        ${wordmark('home.html', true)}
        <p class="rc-footer__line">Processed glass. Ready for its next cycle.</p>
      </div>
      <nav class="rc-footer__nav" aria-label="Footer">
        <ul class="rc-footer__list">
          ${items}
        </ul>
      </nav>
      <address class="rc-footer__address">
        <span>Khasra No. 45/23, 8 Tikri Kalan</span>
        <span>Delhi &ndash; 110041</span>
        <span>India</span>
      </address>
    </div>
    <hr class="rc-rule rc-footer__rule">
    <div class="rc-footer__bottom">
      <p class="rc-small">&copy; ${new Date().getFullYear()} Rian Cullet. All rights reserved.</p>
      <p class="rc-small"><a class="rc-footer__minor" href="#">Privacy Policy</a></p>
    </div>
  </div>
</footer>

${['nav','reveal','hero','counters','process'].map(f => `<script src="${A}/js/${f}.js" defer></script>`).join('\n')}
</body>
</html>`;
}

module.exports = { A, FACTS, NAV, figure, btn, link, eyebrow, head, header, footer };
